/*
	problem 389
	Given two strings s and t which consist of only lowercase letters.
	String t is generated by random shuffling string s and then add one more letter at a random position.
	Find the letter that was added in t.
	Example:
		Input:
		s = "abcd"
		t = "abcde"
		Output:
		e
	Explanation:
	'e' is the letter that was added.
*/

/*
	solution
	to solve this problem, need to convert char to int,
	every char will appear 2 times except the added one,
	therefore, after ^ each char, the added on will be the left one
	same with find unique number
*/
public class FindTheDifference {
    public static void main(String[] args) {
        System.out.println(findTheDifference(args[0], args[1]));
    }

    public static char findTheDifference(String s, String t) {
        char addedChar = '\u0000';
        for (char c : s.toCharArray()) {
            addedChar ^= c;
        }
        for (char c : t.toCharArray()) {
            addedChar ^= c;
        }

        return addedChar;
    }
}